### ISSUE TITLE
Tabs and Image preview are not working

### ISSUE THREAD

**Issue by philxtian** [egonolieux/bootstrap-imageupload#1]
I installed using npm. Imported using browserify. I also imported the CSS but both tabs and image preview are not working. I copy pasted the html code... and also the javascript code from the documentation but still not working.

And by the way, in your documentation you have $('imageupload') -- is it supposed to be $('.imageupload')? (with the class selector)

I like this plugin. Very minimal and simple. Hope I can get this working in my project.

**Comment by egonolieux** [comment]
I installed the npm package in several of my own projects without any issues. Are you correctly including the module using `require('bootstrap-imageupload');`? Are there any errors in your console?

I seem to have forgotten to include the class selector in mij examples indeed. Maybe you copied these examples causing it not to work?

**Comment by philxtian** [comment]
Hi I apologise, I did not take much time to further investigate the issue as I decided to just create my own plugin instead. But to answer your question, yes I did use `require('bootstrap-imageupload')` and also included the class selector.
